name: Output information
on: issues
jobs:
  deatilsoftheissue:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: |
          echo "Issue body:${{ github.event.issue.body }}"
          echo "Issue Title:${{ github.event.issue.title }}"
