name: Understanding Matrix
on: push
jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: understanding matrix include and exlude
        run: |
          echo  "version is": ${{ matrix.version }}
          echo  "os is" ${{ matrix.os }}
      
      
        
