name: Understanding Matrix
on: push
jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pet: [cat, dog]
        color: [pink, brown, white]
        include:
          - color: white
            pet: dog
              
    steps:
      - run: echo "Hello ${{ matrix.color }} ${{ matrix.pet }}"
      
      
        
